### ISSUE TITLE
Lab 2, Exercise 2, Task 2: Slight addition/modification to instructions requested

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure#1]
In Lab 2, Exercise 2, Task 2, the instructions could be modified slightly because the user will need to either:

- Uncheck the box for 'Encrypt connection' in step 1 between sub step g and h to allow the process to work.   

*or* 

- User could leave 'Encrypt connection' checkbox in place and then also select 'Trust server certificate'

This modification to the instructions is requested as (in most all cases) users taking this course will be doing so either on their local laptops, or via hosted/VM/test/SQL servers which will likely not have a specific trusted SSL cert configured & trusted by default, and SQL would instead use the Self_Signed_Fallback cert.

In this scenario, without using one of the instructs mods noted above, they will receive error 'Connection to the server failed.  Validator 'Microsoft.SqlServer.Migration.Core.Validation: failed to validate data....'

**Comment by ctesta-oneillmsft** [comment]
apologies for the delayed response
