### ISSUE TITLE
Lab 3/Exer 4/Task 1 - Drive letter method fails/Version of Data Migration Assistant on VM is out of date

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure#13]
Using the current version of the 'Data Migration Assistant' installed in the VM I was unable to ever get a successful data backup/restore using the drive letter method of 'U:\'.  I had no such problems when using the UNC method of \\dp050storagexxxx.file.core.windows.net\backupshare  

This may be a bug, or my mistake somewhere else, but regardless - The newer versions of the Migration tool, if installed, would necessitate a re-write of these tasks to match.

**Comment by MarkMcGinley760** [comment]
This seems to work now as my students have all completed this step. At the start of the course when first trying to use the Data Migration Assistant it tells you to upgrade the environment to .Net Framework 4.8 and once this is done it updates the DMA when you start it. Maybe that fixes the problem but you have to make sure your fileshare connections from the given xp_cmdshell script reads properly complete beforehand.
