### ISSUE TITLE
Lab 3/Exer 4/Task 2/Step 8 - missing closing apostrophe

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure#14]
In file dp-050-03_instructions.md the referenced step looks like so:

NAME = 'Full Backup of AdventureworksLT2008R2;

needs to have a close apostrophe like so

NAME = 'Full Backup of AdventureworksLT2008R2';

**Comment by rcaper** [comment]
I believe this is actually in step 9 now and has been fixed. Thanks for the feedback!
