### ISSUE TITLE
Lab 4/Exercise 3 ?

### ISSUE THREAD

**Issue by bhmand** [MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure#16]
Is the instructions correct? Are we supposed to migrate from the Azure VM created in lab 3 to a SQL Azure database? Makes no sense and you are not able to configure replication from SSMS on the London server as it needs the actual  server name. to do so.

Regards 
Bobby

**Comment by GeoffAllix** [comment]
This is as intended. The notes make clear that this is not exactly the scenario that you would employ in real life, but setting up a VPN would not teach you any more about SQL Server migrations.

**Comment by bhmand** [comment]
OK I think I did not make my self clear so here goes again. In the beginning of the exercise you are instructed to connect o your Azure VM in SSMS from LON-Dev and then configure replication. This will not work because it needs the actual server name. And it is not clear whether this is needed at all? My students made the migration without configuring replication. So that was actually what I was aiming at. I am perfectly aware of the notes and the normal use of VPN.

**Comment by MarkMcGinley760** [comment]
Yes you are supposed to migrate the data from the SQL VM to the Azure SQL Database. So you need to save the lab environment after Lab3. To get replication on to the SQL VM

1. Connect to the SQL VM in SSMS using the ip address
2. This will allow you to Install Publisher/Distributor on the VM instance
3. To start the SQL Agent you must first check that the Iaas extension is in place (Resource provider microsoft.sqlvirtualmachine must be registered, it should already be done)
4. Run   exec sp_configure 'Agent XPs', 1  Reconfigure;    to get the agent xps installed
5. Refresh the agent and it should show started

The lab doesn't get you to do any replication, just switch it on. The data migration is done through DMS from the portal.

**Comment by bhmand** [comment]
OK so first of all the instructions is not correct as you need to use the IP address. Using the DNS name will not work. And then the students configure replication on the VM instance for no use. Would make more sense that the students then actually replicated the database to Azure.

**Comment by MarkMcGinley760** [comment]
I absolutely agree with you. Once I got replication installed I couldn't get it working, whether it was creating a publication or subscriber. Who is supposed to be checking and updating the material? Or is that us?
The rest of lab 4 is migrating the data but it's not an online migrate as it says, only the Managed Instance will do that as there is an option to Online migrate or Offline migrate. With SQL Database there is only data migration so the lab instructions are confusing to say the least.

**Comment by petender** [comment]
Dear, 
We are currently looking into the reported issues here and will revert back once they have been tested completely again - if there are updates required, I will let you know. Thanks, Peter
