### ISSUE TITLE
Lab 4, Ex 3, Task 2, Step 7: error 5 (access is denied)

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure#17]
Writing to the root directory is bad practice. Service accounts rarely have write permission there.

Replace step 7 with:

```sql
EXEC xp_cmdshell 'md d:\labs';
BACKUP DATABASE AdventureworksLT2008R2 TO DISK = 'd:\labs\awlt2008r2backup.bak';
```

**Comment by rcaper** [comment]
Thanks for the recommendation, I will queue this for the next update.
