### ISSUE TITLE
Lab 4, Ex 1, Task 3, Step 2: Adding family and capacity

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure#18]
Since the code to create a database explicitly specifies the edition, I think it would be good to also show specifying the family and capacity. 

```bash
#creates a general-purpose SQL database
az sql db create --name $labdatabase --resource-group $resourcegroup --server $servername -e GeneralPurpose -f Gen5 -c 2
````

It's just a suggestion, though. I know that the command defaults to Gen5 and 2 vCores. 
Today, at least. Tomorrow it might default to something different. :-)

**Comment by rcaper** [comment]
Thanks for the recommendation, we will address in the next update.
