### ISSUE TITLE
Scenario descriptions in Lab 1

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure#5]
The scenarios in the solution Word document file do not match the ones in the instruction text.

Also, there is a spelling error in the Word document's file name. 

https://github.com/MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure/blob/master/Labfiles/Solution/DP-150.1/Scnarios.docx

**Comment by ctesta-oneillmsft** [comment]
resolved. Thanks
