### ISSUE TITLE
Fenced code blocks with an added space cause .md formatting problems

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure#6]
In several cases I am seeing what I believe to be improper .md formatting wherein an additional space in between a fenced code blocks ``` and the type of code is leading to issues when downstream formatting of the .md takes place.

If possible, can the .md be updated to eliminate these additional spaces?

For example - instead of this:
```shell
test test
```
When there is a problem formatting I see this (note addt'l space between the ``` and the shell:)
``` shell
test text
```

This can be seen in several specific examples in https://raw.githubusercontent.com/MicrosoftLearning/DP-050-Migrating-SQL-Workloads-to-Azure/master/Instruction/dp-050-03_instructions.md

For example:
---------------

**21.	Click save
``` shell
Results: After you completed this exercise you have a SQL Server 2017 instance running in an Azure Virtual Machine.
```
## Exercise 2: Create an Azure Storage Account and Fileshare**

**Comment by rlthompson904** [comment]
#7 pull request should fix this issue if merged.
